// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Academy.Models;

public partial class Discipline
{
    [Key]
    [Column("discipline_id")]
    public short DisciplineId { get; set; }

    [Column("discipline_name")]
    [StringLength(150)]
    public string DisciplineName { get; set; }

    [Column("number_of_lessons")]
    public byte NumberOfLessons { get; set; }
}