// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Academy.Models;

public partial class Group
{
    [Key]
    [Column("group_id")]
    public int GroupId { get; set; }

    [Column("group_name")]
    [StringLength(10)]
    public string GroupName { get; set; }

    [Column("direction", TypeName = "TINYINT")]
    public int? Direction { get; set; }

    [Column("weekdays", TypeName = "TINYINT")]
    public int? Weekdays { get; set; }

    [Column("start_time")]
    [Precision(0)]
    public TimeOnly? StartTime { get; set; }

    [Column("start_date")]
    public DateOnly? StartDate { get; set; }

    [InverseProperty("GroupNavigation")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}