// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Academy.Models;

public partial class PV_521_ImportContext : DbContext
{
    public PV_521_ImportContext(DbContextOptions<PV_521_ImportContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Discipline> Disciplines { get; set; }

    public virtual DbSet<Group> Groups { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Teacher> Teachers { get; set; }

    public virtual DbSet<Direction> Directions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Discipline>(entity =>
        {
            entity.Property(e => e.DisciplineId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Group>(entity =>
        {
            entity.Property(e => e.GroupId).ValueGeneratedNever();
            entity.Property(e => e.GroupName).IsFixedLength();
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.Property(e => e.Phone).IsFixedLength();

            entity.Property(e => e.Photo).HasColumnType("nvarchar(50)");
            entity.Property(e => e.PhotoMimeType).HasMaxLength(50);

            entity.HasOne(d => d.GroupNavigation).WithMany(p => p.Students).HasConstraintName("FK_Students_Groups");
        });

        modelBuilder.Entity<Teacher>(entity =>
        {
            entity.Property(e => e.Phone).IsFixedLength();
            entity.Property(e => e.Photo).HasColumnType("nvarchar(50)");
            entity.Property(e => e.PhotoMimeType).HasMaxLength(50);
        });

        modelBuilder.Entity<Direction>(entity =>
        {
            entity.HasKey(e => e.DirectionId);
            entity.ToTable("Directions");
            entity.Property(e => e.DirectionId).HasColumnName("direction_id");
            entity.Property(e => e.DirectionName)
                .HasColumnName("direction_name")
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}