// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Academy.Models;

public partial class Student
{
    [Key]
    [Column("stud_id")]
    public int StudId { get; set; }

    [Required]
    [Column("last_name")]
    [StringLength(50)]
    public string LastName { get; set; }

    [Required]
    [Column("first_name")]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Column("middle_name")]
    [StringLength(50)]
    public string MiddleName { get; set; }

    [Column("birth_date")]
    public DateOnly BirthDate { get; set; }

    [Column("email")]
    [StringLength(50)]
    public string Email { get; set; }

    [Column("phone")]
    [StringLength(16)]
    public string Phone { get; set; }

    [Column("photo", TypeName = "IMAGE")]
    public byte[] Photo { get; set; }

    [Column("photoMimeType", TypeName = "NVARCHAR(50)")]
    public string PhotoMimeType { get; set; }

    [Column("group")]
    public int? Group { get; set; }

    [ForeignKey("Group")]
    [InverseProperty("Students")]
    public virtual Group GroupNavigation { get; set; }
}